INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(1, 1, 'BAUER BASICS BL PANT-SR-BLK', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(2, 1, 'A&R', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(3, 1, 'Bauer', '96" ', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(4, 1, 'Bauer', '96" 108" 120"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(5, 1, 'Bauer', 'L/XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(6, 1, 'Bauer', 'SR', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(7, 1, 'Bauer', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(8, 1, 'Bauer', 'SR.XXL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(9, 1, 'Bauer', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(10, 1, 'Bauer 4500', 'S', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(11, 1, 'Bauer Basics BL LS TOP', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(12, 1, 'BAUER BASICS BL PANT-SR-BLK', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(13, 1, 'BAUER CORE 1.0 JOCK PANT', 'SR XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(14, 1, 'BAUER CORE 1.0 JOCK SHORT', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(15, 1, 'Bauer Elit Paded Goal LS BL Top', 'SR S', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(16, 1, 'Bauer Essential Comp Jock Pant', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(17, 1, 'Bauer EURO PRO', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(18, 1, 'Bauer Girdle ACP PRO', 'INT L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(19, 1, 'Bauer Girdle ACP PRO', 'SR XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(20, 1, 'Bauer GSX', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(21, 1, 'Bauer HYPERL2', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(22, 1, 'Bauer Nexus 3N', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(23, 1, 'Bauer Nexus E3', 'P28 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(24, 1, 'Bauer Nexus E3', 'P28 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(25, 1, 'Bauer Nexus E5 PRO', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(26, 1, 'Bauer Nexus E5 PRO', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(27, 1, 'Bauer Nexus E5 PRO', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(28, 1, 'Bauer Nexus E5 PRO', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(29, 1, 'Bauer Nexus Geo', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(30, 1, 'Bauer Nexus Geo', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(31, 1, 'Bauer Nexus Geo', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(32, 1, 'Bauer Nexus Geo', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(33, 1, 'Bauer Nexus League', 'P28 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(34, 1, 'Bauer Nexus League', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(35, 1, 'Bauer Nexus League', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(36, 1, 'Bauer Nexus League', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(37, 1, 'Bauer Nexus League', 'P92 95L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(38, 1, 'Bauer Nexus SYNC', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(39, 1, 'Bauer Nexus SYNC', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(40, 1, 'Bauer NLP7', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(41, 1, 'BAUER PERF JOCK PANT-SR', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(42, 1, 'Bauer Performance LOW', 'L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(43, 1, 'Bauer Performance LOW', 'Xl', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(44, 1, 'Bauer Performance LS BL Top', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(45, 1, 'Bauer Performance Tall', 'L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(46, 1, 'Bauer Performance Tall', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(47, 1, 'Bauer Performance Tall', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(48, 1, 'Bauer Premium', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(49, 1, 'Bauer PRO', '11', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(50, 1, 'Bauer PRO', '9F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(51, 1, 'Bauer PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(52, 1, 'Bauer PRO', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(53, 1, 'Bauer PRO ', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(54, 1, 'Bauer PRO 950 ', 'SR.L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(55, 1, 'Bauer PRO 960 ', 'SR.L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(56, 1, 'BAUER PRO LOCKJOCKR PNT SR', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(57, 1, 'BAUER PRO LS BL TOP-SR-BLK', 'Sr S', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(58, 1, 'BAUER PRO SERIES ELBOW PAD - SR', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(59, 1, 'Bauer Profile II Face Mask', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(60, 1, 'Bauer PROTO-V', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(61, 1, 'Bauer Re-Akt 150', 'M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(62, 1, 'Bauer Re-Akt 65', 'M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(63, 1, 'Bauer Re-Akt 95', 'M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(64, 1, 'Bauer Supreme 1S SE', 'P02  112R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(65, 1, 'Bauer Supreme 2S PRO', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(66, 1, 'Bauer Supreme 3S', '16"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(67, 1, 'Bauer Supreme 3S', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(68, 1, 'Bauer Supreme 3S', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(69, 1, 'Bauer Supreme 3S', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(70, 1, 'Bauer Supreme 3S PRO', '14"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(71, 1, 'Bauer Supreme 3S PRO', '16"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(72, 1, 'Bauer Supreme 3S PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(73, 1, 'Bauer Supreme 3S PRO', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(74, 1, 'BAUER SUPREME HEAVYWEIGHT ', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(75, 1, 'BAUER SUPREME HEAVYWEIGHT ', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(76, 1, 'BAUER SUPREME HEAVYWEIGHT ', 'Sr XXL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(77, 1, 'Bauer Supreme M5 PRO', '14"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(78, 1, 'Bauer Supreme M5 PRO', '16"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(79, 1, 'Bauer Supreme M5 PRO', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(80, 1, 'Bauer Supreme M5 PRO', '7 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(81, 1, 'Bauer Supreme M5 PRO', '7 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(82, 1, 'Bauer Supreme M5 PRO', '8 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(83, 1, 'Bauer Supreme M5 PRO', '8,5 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(84, 1, 'Bauer Supreme M5 PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(85, 1, 'Bauer Supreme M5 PRO', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(86, 1, 'Bauer Supreme M5 PRO', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(87, 1, 'Bauer Supreme MACH', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(88, 1, 'Bauer Supreme MACH', 'Sr', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(89, 1, 'Bauer Supreme Ultrasonic', '15"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(90, 1, 'Bauer Supreme Ultrasonic', 'P92 102L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(91, 1, 'Bauer Supreme Ultrasonic', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(92, 1, 'Bauer Supreme Ultrasonic', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(93, 1, 'Bauer Supreme Ultrasonic', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(94, 1, 'Bauer Supreme Ultrasonic', 'Sr.L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(95, 1, 'Bauer Vapor 2X PRO', '14"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(96, 1, 'Bauer Vapor 2X PRO', '15"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(97, 1, 'Bauer Vapor 2X PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(98, 1, 'Bauer Vapor 3X', '16"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(99, 1, 'Bauer Vapor 3X', '8,5 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(100, 1, 'Bauer Vapor 3X', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(101, 1, 'Bauer Vapor 3X ', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(102, 1, 'Bauer Vapor 3X PRO', '16"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(103, 1, 'Bauer Vapor 3X PRO', '7 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(104, 1, 'Bauer Vapor 3X PRO', '8,5 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(105, 1, 'Bauer Vapor 3X PRO', '9 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(106, 1, 'Bauer Vapor 3X PRO', '9,5 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(107, 1, 'Bauer Vapor 3X PRO', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(108, 1, 'Bauer Vapor 3X PRO', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(109, 1, 'Bauer Vapor 3X PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(110, 1, 'Bauer Vapor Hyperlite', '10 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(111, 1, 'Bauer Vapor Hyperlite', '7 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(112, 1, 'Bauer Vapor Hyperlite', '8,5 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(113, 1, 'Bauer Vapor Hyperlite', '9 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(114, 1, 'Bauer Vapor Hyperlite', '9,5 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(115, 1, 'Bauer Vapor Hyperlite', 'INT L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(116, 1, 'Bauer Vapor Hyperlite', 'P92 102L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(117, 1, 'Bauer Vapor Hyperlite', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(118, 1, 'Bauer Vapor Hyperlite', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(119, 1, 'Bauer Vapor Hyperlite', 'Sr XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(120, 1, 'Bauer Vapor Hyperlite', 'Sr.L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(121, 1, 'Bauer Vapor Hyperlite 2', '11 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(122, 1, 'Bauer Vapor Hyperlite 2', '8,5 F2', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(123, 1, 'Bauer Vapor League', 'P28 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(124, 1, 'Bauer Vapor League', 'P92 70L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(125, 1, 'Bauer Vapor League', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(126, 1, 'Bauer Vapor League', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(127, 1, 'Bauer Vapor League', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(128, 1, 'Bauer Vapor League', 'P92 87R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(129, 1, 'Bauer Vapor League', 'P92 95L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(130, 1, 'Bauer Vapor X4', '8 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(131, 1, 'Bauer Vapor X4', '8 F3', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(132, 1, 'Bauer Vapor X4', '8,5 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(133, 1, 'Bauer Vapor X5 PRO', '8,5 F1', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(134, 1, 'Bauer X5 PRO', '26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(135, 1, 'Bauer X5 PRO', 'SR.L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(138, 1, 'BauerTuuk EDGE PULSE ', '263', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(139, 1, 'BauerTuuk EDGELS2', '8,9,10,11', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(140, 1, 'BauerTuuk LS PULSE', '280', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(141, 1, 'CCM ', 'Sr', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(142, 1, 'CCM 3in1', 'Sr', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(143, 1, 'CCM FT 4PRO', 'CUSTOM', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(144, 1, 'CCM FT4 PRO', '14"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(145, 1, 'CCM FT4 PRO', '15"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(146, 1, 'CCM FT4 PRO', 'Sr L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(147, 1, 'CCM FT4 PRO', 'Sr M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(148, 1, 'CCM Jet Speed FT4 PRO', 'SR XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(149, 1, 'CCM PRO', '25"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(150, 1, 'CCM PRO', '25" 26"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(151, 1, 'CCM PRO', '25" 27"', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(152, 1, 'HEYDUK MH 700', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(153, 1, 'HEYDUK MH X', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(154, 1, 'HEYDUK MH300', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(155, 1, 'HEYDUK MH600', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(156, 1, 'HO21 Bauer Warmth Tall', 'L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(157, 1, 'HOWIES', '1L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(158, 1, 'HYPERLITE2', 'SR', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(159, 1, 'HYPERLITE2', 'SR.XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(160, 1, 'MUELLER', '��⠫�', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(161, 1, 'NOW WAX', '108" ', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(162, 1, 'PRO Bauer', '', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(163, 1, 'S19 Bauer Essential Comp Jock Pant', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(164, 1, 'S19 Bauer Essential LOW', 'L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(165, 1, 'S21 Bauer Performance Tall', 'SR L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(166, 1, 'S21 Bauer Performance Tall', 'SR XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(167, 1, 'S22 Bauer Basics BL LS TOP', 'SR L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(168, 1, 'S22 Bauer Basics BL LS TOP', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(169, 1, 'S22 BAUER BASICS BL PANT- -BLK', ' J XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(170, 1, 'S22 BAUER BASICS BL PANT- -BLK', 'SR L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(171, 1, 'S22 BAUER BASICS BL PANT- -BLK', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(172, 1, 'S22 BAUER NEC PROTEC LS BL TOP-SR-BLK', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(173, 1, 'S22 BAUER PERF JOCK PANT-SR', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(174, 1, 'S22 BAUER PERF JOCK PANT-SR', 'SR S', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(175, 1, 'S22 BAUER PERF JOCK PANT-SR', 'SR XL', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(176, 1, 'S22 Bauer Performance LS BL Top', 'SR L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(177, 1, 'S22 BAUER PRO LS BL TOP-SR-BLK', 'SR L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(178, 1, 'S22 BAUER PRO LS BL TOP-SR-BLK', 'SR M', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(179, 1, 'S22 BAUER PRO LS BL TOP-SR-BLK', 'SR S', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(180, 1, 'S23 Bauer Vapor League', 'P92 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(181, 1, 'S23 Bauer Vapor League', 'P92 95L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(182, 1, 'S23 Bauer Vapor X4', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(183, 1, 'S23 Bauer Vapor X4', 'P92 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(184, 1, 'S23 VAPOR X4 GRIP STK-SR-70(60")', 'P28 70L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(185, 1, 'S23 VAPOR X4 GRIP STK-SR-77(60")', 'P28 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(186, 1, 'S23 VAPOR X4 GRIP STK-SR-77(60")', 'P28 77R', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(187, 1, 'S23 VAPOR X4 GRIP STK-SR-77(60")', 'P92 77L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(188, 1, 'S23 VAPOR X4 GRIP STK-SR-87(60")', 'P28 87L', NULL, NULL);
INSERT INTO dr_stick (id, eq_type_ID, stick_name, hand, flex, band) VALUES(189, 1, 'S23 VAPOR X4 GRIP STK-SR-87(60")', 'P92 87L', NULL, NULL);
