INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(1, 2, 'Bauer Vapor 3X PRO', '9', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(2, 2, 'Bauer Supreme M5 PRO', '8', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(3, 2, 'Bauer Vapor Hyperlite', '7', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(4, 2, 'Bauer Vapor 3X PRO', '9,5', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(5, 2, 'Bauer Vapor 3X PRO', '7', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(6, 2, 'Bauer Supreme M5 PRO', '8,5', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(7, 2, 'Bauer Vapor Hyperlite', '9', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(9, 2, 'Bauer Vapor Hyperlite', '10', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(11, 2, 'Bauer Vapor Hyperlite', '9,5', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(12, 2, 'Bauer Vapor Hyperlite', '8,5', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(13, 2, 'Bauer Vapor 3X PRO', '8,5', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(14, 2, 'Bauer Vapor X4', '8', 'F3');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(15, 2, 'Bauer Supreme M5 PRO', '7', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(16, 2, 'Bauer Supreme M5 PRO', '7', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(17, 2, 'Bauer PRO', '9', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(18, 2, 'Bauer Vapor X4', '8', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(19, 2, 'Bauer Vapor X4', '8,5', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(20, 2, 'Bauer Vapor 3X', '8,5', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(22, 2, 'Bauer Vapor Hyperlite 2', '8,5', 'F2');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(23, 2, 'Bauer Vapor X5 PRO', '8,5', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(24, 2, 'Bauer Vapor Hyperlite 2', '11', 'F1');
INSERT INTO dr_skate (id, eq_type_ID, title, sk_size, sk_fit) VALUES(25, 2, 'Bauer PRO', '11', 'F1');