INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(1, 3, 'Bauer Vapor Hyperlite', 'Sr', 'XL', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(2, 3, 'Bauer Supreme Ultrasonic', 'Sr', 'M', '');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(3, 3, 'Bauer Supreme Ultrasonic', 'Sr', 'XL', '');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(5, 3, 'Bauer Supreme 3S', 'Sr', 'XL', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(6, 3, 'Bauer Girdle ACP PRO', 'INT', 'L', '');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(7, 3, 'Bauer Supreme 3S', 'Sr', 'M', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(8, 3, 'Bauer Vapor Hyperlite', 'INT', 'L', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(9, 3, 'Bauer Supreme Ultrasonic', 'Sr', 'M', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(10, 3, 'Bauer Supreme 3S', 'Sr', 'L', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(11, 3, 'Bauer Vapor Hyperlite', 'Sr', 'L', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(12, 3, 'Bauer Vapor Hyperlite', 'SR', 'XL', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(13, 3, 'Bauer Girdle ACP PRO', 'SR', 'XL', '');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(14, 3, 'Bauer Vapor Hyperlite', 'SR', 'L', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(16, 3, 'CCM Jet Speed FT4 PRO', 'SR', 'XL', 'NAV');
INSERT INTO dr_pant (id, eq_type_ID, pant_name, pant_model, pant_size, pant_color) VALUES(17, 3, 'Bauer Supreme 3S', 'Sr', 'L', 'BLK');